version: '3.8'
services:
  postgres_db:
    image: postgres:15-alpine 
    container_name: my_postgres_container 
    restart: always
    environment:
      POSTGRES_USER: mimhkhoi3104
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: de_study  
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: